### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
unsetopt SHARE_HISTORY           # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Dont record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Dont record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Dont write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Dont execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.
setopt NO_HUP                    # Job control for zsh
unsetopt HUP
unsetopt CHECK_JOBS
###

### Dircolors ###
eval $(dircolors ~/.dircolors)

### Editor
export EDITOR=nvim
###

### Java
export _JAVA_AWT_WM_NONREPARENTING=1
###

### LANG
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
###

### Golang
export GOHOME="${HOME}/go"
###

### Path
# Go
export PATH="$PATH:${GOHOME}/bin"

# Rust
export PATH="$PATH:${HOME}/.cargo/bin"

# Terraform
export PATH="$PATH:${HOME}/.terraform"

###

### Aliases
alias grep='rg'
alias vi='nvim'
alias vim='nvim'
alias zinitup='zinit self-update && zinit update --parallel'
alias ls='ls --color=auto'
alias ll='ls -al --color=auto'
alias mvnsc='mvn spotless::apply checkstyle:check org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce -Drules=dependencyConvergence compile test-compile pmd:cpd pmd:pmd javadoc:javadoc pmd:cpd-check pmd:check' 

# plugins
## Syntax highlighting
## ZSH autosuggestions
## ZSH completions
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

zinit for \
    light-mode  zsh-users/zsh-autosuggestions \
    light-mode  zsh-users/zsh-completions \
    light-mode  zdharma-continuum/fast-syntax-highlighting \
                zdharma-continuum/history-search-multi-word \

zinit ice from"gh-r" as"command" atload'eval "$(starship init zsh)"'
zinit load starship/starship

zinit ice from"gh-r" as"program"
zinit light junegunn/fzf

## FZF
zinit ice from"gh-r" as"program"
zinit load junegunn/fzf
