### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
unsetopt SHARE_HISTORY           # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Dont record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Dont record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Dont write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Dont execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.
setopt NO_HUP                    # Job control for zsh
unsetopt HUP
unsetopt CHECK_JOBS
###

### Editor
export EDITOR=nvim
###

### Java
export _JAVA_AWT_WM_NONREPARENTING=1
###

### LANG
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
###

### Golang
export GOHOME="${HOME}/go"
###

### Path
# Go
export PATH="$PATH:${GOHOME}/bin"

# Rust
export PATH="$PATH:${HOME}/.cargo/bin"
export CARGO_NET_GIT_FETCH_WITH_CLI=true

# Terraform
export PATH="$PATH:${HOME}/.terraform"

# Zinit

# Completions
# Git
zi ice lucid wait as'completion' blockf has'git' mv'git-completion.zsh -> _git'
zi snippet https://github.com/git/git/blob/master/contrib/completion/git-completion.zsh
# Docker
zi ice lucid wait as'completion' blockf has"docker"
zi snippet https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker
# Docker compose
zi ice lucid wait as'completion' blockf has"docker-compose"
zi snippet https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose
# fd
zi ice lucid wait as'completion' blockf has"fd"
zi snippet https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/fd/_fd
# Ripgrep
zi ice lucid wait as'completion' blockf has'rg'
zi snippet https://github.com/BurntSushi/ripgrep/blob/master/complete/_rg
# fzf
zi ice lucid wait as'completion' blockf has'fzf' mv'completion.zsh -> _fzf'
zi snippet https://github.com/junegunn/fzf/blob/master/shell/completion.zsh
# paru
zi ice lucid wait as'completion' blockf has'cargo' mv'zsh -> _paru'
zi snippet https://github.com/Morganamilo/paru/blob/master/completions/zsh
# cargo
zi ice lucid wait as'completion' blockf has'cargo'
zi snippet https://github.com/rust-lang/cargo/blob/master/src/etc/_cargo

# Plugins
# Autopair (), '', ""
zi ice wait lucid
zi load hlissner/zsh-autopair
# Dircolors
zi ice atclone"dircolors -b dircolors.ansi-dark > clrs.zsh" \
    atpull'%atclone' pick"clrs.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zi light seebi/dircolors-solarized
# A ls rust
zi ice lucid from"gh-r" as"program" mv"bin/exa* -> exa"
zi light ogham/exa
# A cat clone with syntax highlighting and Git integration.
zi ice from"gh-r" as"command" mv"bat* -> bat" pick"bat/bat"
zi light sharkdp/bat
# A more intuitive version of du written in rust.
zi ice from"gh-r" as"command" mv"dust* -> dust" pick"dust/dust"
zi light bootandy/dust
# A simple, fast and user-friendly alternative to find
zi ice from"gh-r" as"command" mv"fd* -> fd" pick"fd/fd"
zi light sharkdp/fd
# An extremely fast alternative to grep that respects your gitignore
zi ice from"gh-r" as"command" mv"ripgrep* -> rg" pick"rg/rg"
zi light BurntSushi/ripgrep
# A top replacement
zi ice from"gh-r" as"program"
zi light ClementTsang/bottom
# A shell parser, formatter, and interpreter
zi ice from"gh-r" as"program" mv"shfmt* -> shfmt"
zi light mvdan/sh
# Fuzzy searcher
zi ice from"gh-r" as"program"
zi light junegunn/fzf
# Git diff highlighter
zi ice as"command" from"gh-r" mv"delta* -> delta" pick"delta/delta"
zi light dandavison/delta
# Configure as default git diff renderer
git config --global core.pager "delta --dark"

# Theme
## Pure
zi ice compile'(pure|async).zsh' pick'async.zsh' src'pure.zsh'
zi light sindresorhus/pure
# Spaceship
#zi light spaceship-prompt/spaceship-prompt
# Powerlevel10k
#PURE_POWER_MODE=modern
#zi ice depth=1; zi light romkatv/powerlevel10k
#zi snippet https://github.com/sainnhe/dotfiles/raw/master/.zsh-theme/gruvbox-material-dark.zsh

zi light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust \
    zdharma-continuum/history-search-multi-word

zi wait lucid for \
 atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma-continuum/fast-syntax-highlighting \
 blockf \
    zsh-users/zsh-completions \
 atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions

### Aliases
alias grep='rg'
alias cat='bat'
alias du='dust'
alias vi='nvim'
alias vim='nvim'
alias ziup='zi self-update && zi update --parallel'
alias ll='exa -al'
alias l='exa -blF'
alias la='exa -abghilmu'
alias ls='exa -bh --git --group-directories-first'
alias mvnsc='mvn spotless::apply checkstyle:check org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce -Drules=dependencyConvergence compile test-compile pmd:cpd pmd:pmd javadoc:javadoc pmd:cpd-check pmd:check' 
