# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
	colors = true
   color_good = "#888888"
	color_degraded = "#b58900"
	color_bad = "#dc322f"
	color_separator = "#eee8d5"
	interval = 1
}

# order += "disk /"
# order += "wireless wlp3s0"
# order += "ethernet enp0s25"
order += "volume master"
order += "battery 0"
order += "battery 1"
order += "tztime local"

# Wireless info
wireless wlp3s0 {
	format_up = "W: %essid %quality"
   format_down = "W: down"
}

# Ethernet info
ethernet enp0s25 {
	format_up = "E: %ip"
   format_down = "E: down"
}

# Battery 0 info
battery 0 {
	format = "%status [%percentage %remaining]"
	low_threshold = 10
	threshold_type = percent
}

# Battery 1 info
battery 1 {
	format = "%status [%percentage %remaining]"
	low_threshold = 10
	threshold_type = percent
}

# Timezone local time
tztime local {
	format = "%d/%m/%Y %H:%M"
}

# Free space on "/"
disk "/" {
	format = "/ %free"
}

# Volume of machone
volume master {
	device = "default"
	mixer = "Master"
	mixer_idx = 0
}
