---
live_config_reload: true
draw_bold_text_with_bright_colors: true
enable_experimental_conpty_backend: false
# Send ESC (\x1b) before characters when alt is pressed.
alt_send_esc: true

window:
  dynamic_title: true
  dynamic_padding: false
  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #
  # Values for `decorations` (macOS only):
  #   - transparent: Title bar, transparent background and title bar buttons
  #   - buttonless: Title bar, transparent background, but no title bar buttons
  decorations: none
  # When true, alacritty starts maximized.
  startup_mode: Maximized
  opacity: 1

# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    family: Hasklug Nerd Font
    style: Regular
  bold:
    family: Hasklug Nerd Font
    style: Bold
  italic:
    family: Hasklug Nerd Font
    style: Italic
  bold_italic:
    family: Hasklug Nerd Font
    style: Bold Italic
  size: 13.0

debug:
  # Display the time it takes to redraw each frame.
  render_timer: false
  # Keep the log file after quitting Alacritty.
  persistent_logging: false
  # Log level
  #
  # Values for `log_level`:
  #   - None
  #   - Error
  #   - Warn
  #   - Info
  #   - Debug
  #   - Trace
  log_level: Warn
  # Print all received window events.
  print_events: false
  # Record all characters and escape sequences as test data.
  ref_test: false

# Colors (Gruvbox Dark Material)
colors:
  primary:
    background: '#282828'
    foreground: '#d4be98'

  selection:
    text: CellForeground
    background: '#665c54'

  normal:
    black: '#3c3836'
    red: '#ea6962'
    green: '#a9b665'
    yellow: '#d8a657'
    blue: '#7daea3'
    magenta: '#d3869b'
    cyan: '#89b482'
    white: '#d4be98'

  bright:
    black: '#665c54'
    red: '#ea6962'
    green: '#a9b665'
    yellow: '#d8a657'
    blue: '#7daea3'
    magenta: '#d3869b'
    cyan: '#89b482'
    white: '#d4be98'

mouse_bindings:
  - {mouse: Middle, action: PasteSelection}

mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: {threshold: 300}
  triple_click: {threshold: 300}
  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true
  hints:
    # URL launcher
    #
    # This program is executed when clicking on a text which is
    # recognized as a URL.
    # The URL is always added to the command as the last parameter.
    #
    # When set to `None`, URL launching will be disabled completely.
    #
    # Default:
    #   - (macOS) open
    #   - (Linux) xdg-open
    #   - (Windows) explorer
    launcher:
      program: xdg-open
      args: []
    # URL modifiers
    #
    # These are the modifiers that need to be held down
    # for opening URLs when clicking
    # on them. The available modifiers are documented
    # in the key binding section.
    modifiers: None

cursor:
  style:
    shape: Block
  vi_mode_style: Block
