#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_topmost               on
yabai -m config window_placement             second_child
yabai -m config window_opacity               off
yabai -m config window_shadow                float
yabai -m config window_border                off
yabai -m config window_border_placement      interior
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.80
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   5

# rules for apps
yabai -m rule --add app="^Brave Browser" space=3
yabai -m rule --add app="^Slack" space=4
yabai -m rule --add app="^Music$" display=^4


echo "yabai configuration loaded.."
