export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

# Start completions
fpath=(/usr/local/share/zsh-completions $fpath)

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
unsetopt SHARE_HISTORY           # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Dont record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Dont record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Dont write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Dont execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.
setopt NO_HUP                    # Job control for zsh
unsetopt HUP
unsetopt CHECK_JOBS

# Plugins
zplug 'zplug/zplug', hook-build:'zplug --self-manage'
zplug "plugins/git", from:oh-my-zsh
zplug "mafredri/zsh-async", from:github
zplug "zsh-users/zsh-completions", from:github, defer:2
zplug "zsh-users/zsh-autosuggestions", from:github, defer:2
zplug "zsh-users/zsh-syntax-highlighting", from:github, defer:2
zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme

# Dircolors
eval $(gdircolors ~/.dir_colors)

# Editor
export EDITOR=vi

# LANG
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

# Path
export PATH=$PATH:/usr/local/opt/go/libexec/bin

# Aliases
alias ls='gls --color=auto'
alias grep='ggrep'
alias ll='ls -al'
alias vi='nvim'
alias vim='nvim'
alias brewup='brew update && brew upgrade && brew cu && brew cleanup; brew doctor'
alias dc='docker-compose'

zplug load

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
