general {
        colors = true
        color_good = "#98971a"
        color_bad = "#cc241d"
        color_degraded = "#fabd2f"
        interval = 1
}

# order += "disk /"
# order += "wireless wlp3s0"
# order += "ethernet enp0s25"
order += "volume master"
order += "battery 0"
order += "tztime local"

# Wireless info
wireless wlp3s0 {
	format_up = "W: %essid %quality"
    format_down = "W: down"
}

# Ethernet info
ethernet enp0s25 {
	format_up = "E: %ip"
	format_down = "E: down"
}

# Battery 0 info
battery 0 {
	format = "%status %percentage %remaining"
    format_down = "No battery"
    status_chr = "⚇ CHR"
    status_bat = "⚡ BAT"
    status_full = "☻ FULL"
    low_threshold = 10
	threshold_type = percent
}

# Timezone local time
tztime local {
	format = "%d/%m/%Y %H:%M"
}

# Free space on "/"
disk "/" {
	format = "/ %free"
}

# Volume of machone
volume master {
	device = "default"
	mixer = "Master"
	mixer_idx = 0
}
